name: continuous_integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
      
      - name: Install Dependencies
        run: 
          pip install -r project-1/requirements.txt
          pip install pytest pytest-cov

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: test_script
        run: |
          project-1/test_gspread_code.py
      - name: Check test Coverage
          python3 -m pytest --cov-report term --cov-report xml:coverage.xml --cov=project-1/gspread_code.py
